linters-settings:
  cyclop:
    max-complexity: 20
  gocognit:
    min-complexity: 50
  goconst:
    min-occurrences: 8
  funlen:
    lines: 150
    statements: 50
  varnamelen:
    ignore-names:
      - id
linters:
  enable:
    - asasalint
    - bidichk
    # - bodyclose
    - containedctx
    # - contextcheck
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - makezero
    - nakedret
    - nestif
    # - nilerr
    - nilnil
    - nlreturn
    # - noctx
    - nolintlint
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    # - rowserrcheck
    # - sqlclosecheck
    # - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    # - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - varnamelen
    # - wastedassign
    - whitespace
    - wrapcheck
    - wsl
